# Generated by Django 5.2.5 on 2025-12-08 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layanan', models.CharField(max_length=100)),
                ('proses', models.IntegerField(default=0)),
                ('prediksi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrean.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Antrean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_antrean', models.CharField(max_length=20)),
                ('status', models.CharField(default='Menunggu', max_length=50)),
                ('panggil', models.BooleanField(default=False)),
                ('tgl_daftar', models.DateTimeField(default=django.utils.timezone.now)),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai_otomatis', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('durasi_pelayanan', models.IntegerField(blank=True, null=True)),
                ('prediksi_mlr', models.IntegerField(blank=True, null=True)),
                ('error_mlr', models.IntegerField(blank=True, null=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrean.layanan')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrean.mahasiswa')),
            ],
        ),
    ]
